osx_image: xcode9.4
language: objective-c
env:
  global:
    - PROJECT="Tagging.xcodeproj"
    - SCHEME="Tagging"
    - IOS_SDK="iphonesimulator"
  matrix:
    - SDK="$IOS_SDK"  DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=11.4"

install:
  - swift --version

before_script:
  - set -o pipefail

script:
    - xcodebuild clean build test
      -project "$PROJECT"
      -scheme "$SCHEME"
      -sdk "$SDK"
      -destination "$DESTINATION" | xcpretty -c